categories:
  captchafox: ~

settings:
  captchafox.siteKey:
    default: ''
    type: string
    category: captchafox
  captchafox.secretKey:
    default: ''
    type: string
    category: captchafox
