services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CaptchaFox\CaptchaFoxTypo3\:
    resource: '../Classes/*'
    # Form elements are created by the form framework, the others are plain value objects and helpers.
    exclude: '../Classes/{Domain/Model,Verification,Language}/*'

  CaptchaFox\CaptchaFoxTypo3\Services\CaptchaService:
    public: true

  CaptchaFox\CaptchaFoxTypo3\ViewHelpers\Form\CaptchaFoxViewHelper:
    public: true

  CaptchaFox\CaptchaFoxTypo3\Validation\CaptchaFoxValidator:
    public: true
    shared: false
