services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CaptchaFox\CaptchaFoxTypo3\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  CaptchaFox\CaptchaFoxTypo3\Services\CaptchaService:
    public: true
    arguments:
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $requestFactory: '@TYPO3\CMS\Core\Http\RequestFactory'

  CaptchaFox\CaptchaFoxTypo3\ViewHelpers\Form\CaptchaFoxViewHelper:
    public: true
    arguments:
      $captchaService: '@CaptchaFox\CaptchaFoxTypo3\Services\CaptchaService'

  CaptchaFox\CaptchaFoxTypo3\Validation\CaptchaFoxValidator:
    public: true
